version: '3'
services:
  postgres_db:
    image: 'postgres'
    container_name: postgres_db
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    volumes:
      - ./postgres:/var/www/html
    ports:
      - 5432:5432
    networks:
      - docker-laboratory

  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - 2181:2181
    networks:
      - docker-laboratory

  kafka:
    image: wurstmeister/kafka:2.11-1.1.0
    container_name: kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: create-laboratory:1:1, find-all-laboratory:1:1, create-exam:1:1, find-all-exam:1:1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - docker-laboratory

  exam-engine:
    image: biojj/exam-engine
    container_name: exam-engine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    networks:
      - docker-laboratory

  laboratory-engine:
    image: biojj/laboratory-engine
    container_name: laboratory-engine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    networks:
      - docker-laboratory

  notification-engine:
    image: biojj/notification-engine
    container_name: notification-engine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    restart: always
    networks:
      - docker-laboratory

  api:
    image: biojj/laboratory-api
    container_name: laboratory-api
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    ports:
      - 3000:3000
    networks:
      - docker-laboratory
    depends_on:
      - postgres_db
      - laboratory-engine
      - exam-engine

networks:
  docker-laboratory:
    driver: bridge
